title: ""
description: "Academic website"

# Use the GitHub Pages compatible version
remote_theme: just-the-docs/just-the-docs

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-remote-theme


